package com.example.SplitBills.enums;

public enum ErrorType {
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INCORRECT_PASSWORD,
    VALIDATION_ERROR,
    YOU_ARE_NOT_YOUR_FRIEND,
    GROUP_NOT_FOUND,
    NOT_YOUR_GROUP,
    TOO_MANY_REQUESTS,
    BAD_REFRESH_TOKEN,
    UNAUTHORIZED_ACCESS,
    INVALID_PAYMENT_OPERATION,
    PAYMENT_NOT_FOUND
}
