app:
  base-url: ${APP_BASE_URL}

spring:
  application:
    name: SplitBills

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: splitbills-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.SplitBills.*"
        spring.json.use.type.headers: false

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: INFO
    liquibase: DEBUG
    org.springframework.kafka: INFO